main-group-25-req-9-10-11
tryber/sd-07-project-recipes-app pull request #317
Opened 2021-01-28 21:31 UTC by BrunoDantasS

2021-01-28 23:53 UTC, eriquyjhordan requested changes
Bruno, quando puder verifique se os testes estão passando localmente, aqui no avaliador do PR ainda não passaram

2021-01-28 23:53 UTC, eriquyjhordan commented on src/scenes/Header/components/TitleHeader.js
> +  ajustingStatesWithH1() {
Bruno, considere trocar essas verificações para um Switch Case, pois da forma que está implementado todas as condições são verificadas como o app é pequeno não temos problemas de perfomance, mas conforme ele for crescendo impactará a aplicação.

2021-01-28 23:53 UTC, eriquyjhordan commented on src/scenes/Header/components/SearchButton.js
> +      {(pathname !== ('/explorar')
Bruno, outra sugestão seria passar uma propriedade booleana para o componente Header para informar se o SearchButton deve ou não aparecer, acredito que isto irá diminuir a complexidade do código.

2021-02-01 15:33 UTC, kramerProject commented on src/common/Header/components/SearchButton.js
> +        && pathname !== ('/receitas-favoritas'))
Fala Bruno, tudo bem?. Apenas como sugestão você poderia passar duas propriedades para o header, um título e um boolean que vai controlar se o search button aparece ou não na página. A idéia seria reduzir seu código com as verificações do path.

2021-02-01 15:43 UTC, kramerProject commented on src/common/Header/components/TitleHeader.js
> +  ajustingStateH1() {
Apenas como sugestão você poderia passar duas propriedades para o header, um título e um boolean que vai controlar se o search button aparece ou não na página. Com isso você poderia eliminar o switch, por que o título viria da página que chamar esse componente, aqui um Exemplo de chamada do header com e sem search button: da página de comidas <Header tittle="Comidas" hasSearch={true} />, da página de explorar comidas <Header title="Explorar Comidas" hasSearch="false" />.

2021-02-01 15:44 UTC, kramerProject commented on src/common/Header/components/TitleHeader.js
> +  ajustingStateH1() {
nossa não foi o exemplo. `<Header title="Comidas" hasSearch={true}`

2021-02-01 15:46 UTC, kramerProject commented on src/common/Header/components/TitleHeader.js
> +  ajustingStateH1() {
e do explorar comidas ficaria assim.`<Header title="Explorar Comidas" hasSearch={false}` ou colocar um default pra essa propriedade.

2021-02-01 15:48 UTC, kramerProject commented on src/tests/Header.test.js
> +describe('Teste do Header.js', () => {
Bacana que já fez os testes!

2021-02-01 17:22 UTC, eriquyjhordan approved these changes

2021-02-01 17:22 UTC, danwhat approved these changes

2021-02-01 17:23 UTC, merged