Main group 15 footer
tryber/sd-07-project-recipes-app pull request #496
Opened 2021-01-30 16:09 UTC by Galaraz

2021-01-30 22:03 UTC, Scriblet requested changes

2021-01-30 22:03 UTC, Scriblet commented on .eslintrc.json
> +    "react/jsx-max-depth": ["error", {"max": 5}],
João por que tu ta mudando o arquivo do Avaliador? Muda isso aqui mano

2021-02-01 18:54 UTC, Scriblet approved these changes

2021-02-01 18:58 UTC, Galaraz commented
ae

2021-02-01 18:58 UTC, merged