requisitos
tryber/sd-07-project-recipes-app pull request #633
Opened 2021-02-02 20:29 UTC by Galaraz

do 82 a 86

2021-02-02 20:33 UTC, Scriblet requested changes

2021-02-02 20:33 UTC, Scriblet commented on src/pages/Perfil/index.js
> +          <h1 data-testid="profile-email">email@email</h1>
@Galaraz Nesse campo tem que vir o Email que tá lá no Store da Login Page, assim tá mockando um resultado, consegue puxar lá do store para cá?

2021-02-02 20:34 UTC, Galaraz commented on src/pages/Perfil/index.js
> +          <h1 data-testid="profile-email">email@email</h1>
sim esse e o 82 e 87 em breve vou subir

2021-02-03 21:03 UTC, Scriblet approved these changes

2021-02-03 21:03 UTC, QuintilianoDalete approved these changes

2021-02-03 21:03 UTC, merged