receitas em processo
tryber/sd-07-project-recipes-app pull request #866
Opened 2021-02-05 18:59 UTC by Galaraz

2021-02-06 16:56 UTC, Galaraz commented
-Criação de rotas
-Página receita em processo (funcional) 
-Adição do footer a tela comida para versão  vigente 

proximo passos :
ajuste para passar nos requisitos

2021-02-07 18:34 UTC, Scriblet requested changes

2021-02-07 18:34 UTC, Scriblet commented on src/pages/TelaReceitasEmProcesso/index.js
> +  handleTime() {
Como essa função está sendo chamada na linha 75 não era para ela estar descomentada aqui?

2021-02-07 18:51 UTC, Galaraz commented on src/pages/TelaReceitasEmProcesso/index.js
> +  handleTime() {
Sim preciso adicionar funções ainda... da forma como esta ele esta rondando, subi a pedido do quintiliano para uso do mesmo

2021-02-07 19:32 UTC, Scriblet approved these changes

2021-02-08 11:43 UTC, Galaraz commented
O que foi feito :

- [ ] adição da lógica de redirecionamento (ainda não terminado  crasha a ser direcionado)
- [x] logica do tipo descomentada e funcional 

proximo passos :
-ajuste para passar nos requisitos

2021-02-08 21:10 UTC, merged